### ISSUE TITLE
Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by TheMassassian** [marcel-devdude/mite-api#1]
Hello @marcel-devdude,

I keep getting the following error: [Error: Hostname/IP doesn't match certificate's altnames]

```
mite.getCustomers(options, function(err, res){
    console.log(err);
    console.log(res);
});
```

Just followed the first steps using my account.

Greetings, 

theMassassian

**Comment by Ephigenia** [comment]
Doesn’t seem that someone else had these problems. If you still encounter this error please provide which hostname’s or ips / certificates you’re using. Thanks.
